Branch for home task3
Lexxxxxxa/HomeTask1 pull request #3
Opened 2023-11-19 17:51 UTC by Lexxxxxxa

2023-11-20 13:21 UTC, Delvin09 requested changes

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Task1-5.cs
> +        public string Suit { get; set; }
Лучше через enum'ы. Так меньше будет возни со строками. Ну и производительнее.

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Task1-5.cs
> +    public class Card
Лучше вынести типы в отдельные файлы

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Task1-5.cs
> +    public class Card
А почему не структура?)

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Task1-5.cs
> +        public List<Card> Deck;
поля с маленькой

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Task1-5.cs
> +            foreach (Card card in Deck)
лучше через for, IndexOf будет снова проходить по кол-ии в поисках индекса

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Task1-5.cs
> +        public void SwitchAllClubsOnBeginning(int clubIndex = 0)
а зачем параметра?

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Program.cs
> +            Console.WriteLine("Welcome to 'Game21'! :-]");
По моему, этот код тоже можно вынести в класс Игра

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Program.cs
> +            int gamesPlayed = 0;
Я думаю, что не хватает еще и класса Игрок

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Game21.cs
> +        public static int PlayRound()
Давай не будем делать статику

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Game21.cs
> +        public static int PlayRound()
Пускай Игра создается, и делает то что ей нужно, а утилитарные методы, можно сделать статическими.

2023-11-20 13:21 UTC, Delvin09 commented on HomeTask4/Game21.cs
> +        public static int PlayRound()
int в качестве возвращаемого значения не очень информативно. Я так понимаю, что тут должен быть Игрок который выиграл. Т.е. еще один плюс к созданию класса Игрок.

2023-11-22 09:24 UTC, Delvin09 requested changes

2023-11-22 09:24 UTC, Delvin09 commented on HomeTask4/Enum.cs
> +    public class Enum
а зачем класс? можно же неймспейс поменять: HomeTask4.Enum

2023-11-22 09:24 UTC, Delvin09 commented on HomeTask4/Card.cs
> +        public Enum.Suit Suit { get; set; }
думаю, что для этих свойств сеттера не должно быть

2023-11-22 09:24 UTC, Delvin09 commented on HomeTask4/CardDeck.cs
> +        public List<Card> deck;
это поле, давай его сделаем приватным.

2023-11-22 09:24 UTC, Delvin09 commented on HomeTask4/CardDeck.cs
> +        public List<Card> cards => deck;
это свойство, давай его оставим публичным, но поменяем в названии первую букву на большую, чтобы не путать его с полями.
А вообще, не стоит так просто возвращать список. Я бы вернул deck.AsReadOnly()

2023-11-22 09:24 UTC, Delvin09 commented on HomeTask4/CardDeck.cs
> +        public Enum.Suit[] Suits = { Enum.Suit.Spades, Enum.Suit.Hearts, Enum.Suit.Diamonds, Enum.Suit.Clubs };
1. Не думаю, что есть необходимость в таких публичных полях. Лучше их сделать приватными и readonly.
2. Для получения массива всех значений перечисления, можно использовать: `Enum.GetValues<Suit>()`

2023-11-22 09:24 UTC, Delvin09 commented on HomeTask4/CardDeck.cs
> +            List<int> acePositions = deck
хитро, но в методе SwitchAllClubsOnBeginning, такой же код, почему бы не обобщить?

2023-11-22 09:24 UTC, Delvin09 commented on HomeTask4/Game21.cs
> +            int temp = 0;
Я думал, что взятие карты, это процесс который относится к колоде и/или игроку.

2023-11-22 09:24 UTC, Delvin09 commented on HomeTask4/Player.cs
> +        public int Points { get; private set; }
Я думал, что у игрока будут его карты. Тогда Points будут вычисляться на основе "Руки" игрока.

2023-11-22 10:14 UTC, Lexxxxxxa commented on HomeTask4/CardDeck.cs
> +        public Enum.Suit[] Suits = { Enum.Suit.Spades, Enum.Suit.Hearts, Enum.Suit.Diamonds, Enum.Suit.Clubs };
2. уже пытался так сделать но столкнулся с ошибкой The type or namespace name 'GetValues' does not exist in the namespace 'HomeTask4.Enum' (are you missing an assembly reference?)

2023-11-23 14:52 UTC, Delvin09 approved these changes

2023-11-23 14:52 UTC, Delvin09 commented on HomeTask4/CardDeck.cs
> +        private List<Card> Deck;
это поле, пиши с маленькой) а то в коде ниже можно решить что это свойство.

2023-11-23 14:52 UTC, Delvin09 commented on HomeTask4/CardDeck.cs
> +            foreach (Suit suit in Suits)
можно через Enum.GetValues<>() получить все значения перечислений

2023-11-26 07:25 UTC, merged